import { build } from 'esbuild'

await build({
  entryPoints: ['src/main.ts'],
  bundle: true,
  format: 'esm',
  platform: 'browser',
  target: 'es2022',
  outfile: 'www/js/app.js',
  external: ['./sync-core.js'],   // copied separately into www/js by build-apk.sh
  banner: { js: '// GENERATED by mobile/build.mjs — do not edit. Source: mobile/src/' },
})
console.log('built www/js/app.js')
