import { build } from 'esbuild'

await build({
  entryPoints: ['src/index.ts'],
  bundle: true,
  format: 'esm',
  platform: 'browser',
  target: 'es2022',
  outfile: '../static/js/productivity/sync-core.js',
  banner: { js: '// GENERATED by sync-engine/build.mjs — do not edit by hand. Source: sync-engine/src/' },
})
console.log('built static/js/productivity/sync-core.js')
